"""Routines — materialised projection of customer ``.ship/config.yml`` routines.

The backend maintains one :class:`Routine` row per ``(repo, routine_id)`` by
periodically (or webhook-driven) pulling ``.ship/config.yml`` from the
customer's default branch, parsing ``process.routines``, and
upserting. See :mod:`backend.app.services.lanes_sync` for the sync
logic.

This is *not* the authoritative source — the file in the repo is.
Routine rows are a cache that:

- lets the Console render declared lanes (including custom,
  non-starter ones) without a GitHub round-trip per request,
- gives ``workflow_run.completed`` webhook reconciliation a stable
  key (``(repo_id, lane_id)``) to pin "last run" data against, and
- anchors a future "Trigger this lane" button via the new
  ``PipelineRun.lane_id`` FK.

A lane is intentionally thinner than a ``Pipeline``:

- no ``enabled`` toggle from the UI — the lane exists iff the YAML
  declares it (mirroring "config is the spec" from RFC-0007);
- ``enabled`` on the row tracks a future soft-disable (writes land
  in Phase 7+), not the presence of the lane;
- no ``workflow_id`` — a lane maps to one ``pattern``, and the thin
  GitHub Actions wrapper is generated by ``shipctl lanes install``
  rather than catalog-resolved.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from typing import Final

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    String,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.app.db.base import Base
from backend.app.db.models.integrations import WorkspaceRepo
from backend.app.db.models.tenancy import (
    Workspace,
    _pk,  # noqa: PLC2701  — shared column helper, intra-package.
    _ts_created,  # noqa: PLC2701
    _ts_updated,  # noqa: PLC2701
)


class Routine(Base):
    """One routine declared in a repo's ``.ship/config.yml``.

    The tuple ``(repo_id, routine_id)`` is unique. The Python attribute is
    still named ``lane_id`` while the API is being cleaned up, but the database
    column is ``routine_id`` after migration 0041.

        lanes:
          pr_review:
            event: pull_request
            pattern: pr-and-ci-gate

    ``pattern`` is denormalised out of the raw config for cheaper
    joins against the catalog; the full config dict stays in
    ``config_blob`` so the Console can render forward-compatible
    fields (e.g. ``inputs:``, ``timeout:`` once schema v2.x grows
    them) without a schema change.
    """

    __tablename__ = "routines"
    __table_args__ = (
        UniqueConstraint("repo_id", "routine_id", name="uq_routines_repo_routine"),
        CheckConstraint(
            "kind IN ('once', 'event', 'schedule')",
            name="ck_routines_kind",
        ),
        # Mirrors the migration in 0035_lane_origin.py — keep both in
        # lockstep with :data:`_LANE_ORIGIN_VALUES`.
        CheckConstraint(
            "origin IN ('merged', 'wizard_seed_synthetic', 'manual')",
            name="ck_routines_origin",
        ),
        Index("ix_routines_workspace_id", "workspace_id"),
        Index("ix_routines_repo_id", "repo_id"),
        Index("ix_routines_repo_origin", "repo_id", "origin"),
    )

    id: Mapped[uuid.UUID] = _pk()
    workspace_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("workspaces.id", ondelete="CASCADE"),
        nullable=False,
    )
    repo_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("workspace_repos.id", ondelete="CASCADE"),
        nullable=False,
    )
    # Routine id from ``process.routines``. Attribute remains ``lane_id`` for
    # compatibility with older service code during the DB migration.
    lane_id: Mapped[str] = mapped_column("routine_id", String(64), nullable=False)
    # ``once`` = one-shot install-time task, ``event`` = webhook-driven
    # (pull_request / push / …), ``schedule`` = cron. Matches the
    # discriminator used by :mod:`cli.lib.commands.lanes`.
    kind: Mapped[str] = mapped_column(String(16), nullable=False)
    pattern: Mapped[str | None] = mapped_column(String(255), nullable=True)
    # ``schedule`` lanes only; 5-field UTC cron (``schedule: "0 9 * * *"``).
    cron: Mapped[str | None] = mapped_column(String(128), nullable=True)
    # ``once`` lanes only; opaque string that callers compare against
    # a ledger so reseeds don't fire twice.
    idempotency_key: Mapped[str | None] = mapped_column(
        String(255), nullable=True
    )
    enabled: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("true")
    )
    # Provenance for the row. ``'merged'`` = derived from a merged
    # ``.ship/config.yml`` (the historical-only path); the wizard
    # writes ``'wizard_seed_synthetic'`` BEFORE the seed PR merges so
    # the Inbox / Coverage / Automations UIs aren't empty on day one
    # (Wave 8b P5-07). ``'manual'`` is reserved for the future
    # admin-add flow. The post-merge syncer is allowed to flip
    # ``'wizard_seed_synthetic'`` → ``'merged'`` in place when the
    # config still references the same lane (no row replacement
    # preserves ``last_run_at`` / ``last_run_status``).
    origin: Mapped[str] = mapped_column(
        String(32),
        nullable=False,
        server_default=text("'merged'"),
    )
    config_blob: Mapped[dict] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )

    last_run_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    last_run_status: Mapped[str | None] = mapped_column(
        String(32), nullable=True
    )

    synced_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )
    # ``<ref_sha>:<path>`` where we pulled the config from. Powers the
    # Console's freshness badge and lets the webhook reconciler skip
    # a fetch when the SHA matches.
    sync_source: Mapped[str | None] = mapped_column(String(255), nullable=True)

    created_at: Mapped[datetime] = _ts_created()
    updated_at: Mapped[datetime] = _ts_updated()

    workspace: Mapped[Workspace] = relationship()
    repo: Mapped[WorkspaceRepo] = relationship()


_LANE_ORIGIN_VALUES: Final[tuple[str, ...]] = (
    # ``.ship/config.yml`` on the default branch declared this lane
    # (the only path before P5-07 — every existing row carries this
    # value via the migration's ``server_default``).
    "merged",
    # The wizard wrote this lane from :data:`DEFAULT_BUNDLE` BEFORE
    # the seed PR merged (or even opened). The post-merge syncer is
    # expected to promote it to ``'merged'`` once the merged config
    # references the same lane id.
    "wizard_seed_synthetic",
    # Operator added the lane by hand via a future admin surface.
    # Reserved name; no producer in P5-07.
    "manual",
)


class RoutineRun(Base):
    """One execution of a :class:`Routine`.

    Replaces the retired ``PipelineRun`` model. Same lifecycle —
    inserted as ``status='running'`` when the Console "Run now"
    button fires (or when the GitHub Actions workflow_dispatch
    hits the routine via the cron path), transitioned to
    ``succeeded`` / ``failed`` on the callback from the GHA
    workflow. The runner is the workflow_dispatch handler in
    ``routes/runs.py``; this row is the audit trail + status
    surface the dashboard renders.
    """

    __tablename__ = "routine_runs"
    __table_args__ = (
        Index(
            "ix_routine_runs_routine_started",
            "routine_id",
            "started_at",
        ),
        Index("ix_routine_runs_workspace_id", "workspace_id"),
    )

    id: Mapped[uuid.UUID] = _pk()
    routine_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("routines.id", ondelete="CASCADE"),
        nullable=False,
    )
    # Denormalised for cheap "all runs in workspace" queries; the
    # FK above carries correctness.
    workspace_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("workspaces.id", ondelete="CASCADE"),
        nullable=False,
    )
    # ``manual`` (button), ``webhook`` (PR / workflow_run reconcile),
    # ``cron`` (scheduled dispatch), ``onboarding`` (auto-seed run).
    trigger: Mapped[str] = mapped_column(String(32), nullable=False)
    status: Mapped[str] = mapped_column(String(32), nullable=False)
    started_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    finished_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    summary: Mapped[str | None] = mapped_column(String(1024), nullable=True)
    payload: Mapped[dict] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    # RFC-0010 §RunSummary outcome contract — drives the Runs list
    # row layout + inbox intake approval / escalation decisions.
    outcome: Mapped[dict] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )
    # SHA-256 of the short-lived JWT we hand to the dispatched
    # workflow via ``inputs.ship_run_token``. The callback endpoint
    # rejects anything that doesn't match.
    run_token_hash: Mapped[str | None] = mapped_column(
        String(64), nullable=True
    )

    created_at: Mapped[datetime] = _ts_created()
    updated_at: Mapped[datetime] = _ts_updated()


__all__ = ["Routine", "RoutineRun", "_LANE_ORIGIN_VALUES"]
