"""Lanes — materialised projection of customer ``.ship/config.yml`` lanes (RFC-0007 Phase 7).

The backend maintains one :class:`Lane` row per ``(repo, lane_id)`` by
periodically (or webhook-driven) pulling ``.ship/config.yml`` from the
customer's default branch, parsing the v2 ``lanes:`` section, and
upserting. See :mod:`backend.app.services.lanes_sync` for the sync
logic.

This is *not* the authoritative source — the file in the repo is.
Lane rows are a cache that:

- lets the Console render declared lanes (including custom,
  non-starter ones) without a GitHub round-trip per request,
- gives ``workflow_run.completed`` webhook reconciliation a stable
  key (``(repo_id, lane_id)``) to pin "last run" data against, and
- anchors a future "Trigger this lane" button via the new
  ``PipelineRun.lane_id`` FK.

A lane is intentionally thinner than a ``Pipeline``:

- no ``enabled`` toggle from the UI — the lane exists iff the YAML
  declares it (mirroring "config is the spec" from RFC-0007);
- ``enabled`` on the row tracks a future soft-disable (writes land
  in Phase 7+), not the presence of the lane;
- no ``workflow_id`` — a lane maps to one ``pattern``, and the thin
  GitHub Actions wrapper is generated by ``shipctl lanes install``
  rather than catalog-resolved.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    String,
    UniqueConstraint,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from backend.app.db.base import Base
from backend.app.db.models.integrations import WorkspaceRepo
from backend.app.db.models.tenancy import (
    Workspace,
    _pk,  # noqa: PLC2701  — shared column helper, intra-package.
    _ts_created,  # noqa: PLC2701
    _ts_updated,  # noqa: PLC2701
)


class Lane(Base):
    """One lane declared in a repo's ``.ship/config.yml``.

    The tuple ``(repo_id, lane_id)`` is unique. ``lane_id`` is the
    YAML key under ``lanes:`` in config v2 — e.g. ``pr_review`` in::

        lanes:
          pr_review:
            event: pull_request
            pattern: pr-and-ci-gate

    ``pattern`` is denormalised out of the raw config for cheaper
    joins against the catalog; the full config dict stays in
    ``config_blob`` so the Console can render forward-compatible
    fields (e.g. ``inputs:``, ``timeout:`` once schema v2.x grows
    them) without a schema change.
    """

    __tablename__ = "lanes"
    __table_args__ = (
        UniqueConstraint("repo_id", "lane_id", name="uq_lanes_repo_lane"),
        CheckConstraint(
            "kind IN ('once', 'event', 'schedule')",
            name="ck_lanes_kind",
        ),
        Index("ix_lanes_workspace_id", "workspace_id"),
        Index("ix_lanes_repo_id", "repo_id"),
    )

    id: Mapped[uuid.UUID] = _pk()
    workspace_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("workspaces.id", ondelete="CASCADE"),
        nullable=False,
    )
    repo_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("workspace_repos.id", ondelete="CASCADE"),
        nullable=False,
    )
    # YAML key from ``lanes:`` — matches ``shipctl run <lane_id>`` and
    # is embedded in the generated wrapper path
    # ``.github/workflows/ship-<lane_id>.yml``.
    lane_id: Mapped[str] = mapped_column(String(64), nullable=False)
    # ``once`` = one-shot install-time task, ``event`` = webhook-driven
    # (pull_request / push / …), ``schedule`` = cron. Matches the
    # discriminator used by :mod:`cli.lib.commands.lanes`.
    kind: Mapped[str] = mapped_column(String(16), nullable=False)
    pattern: Mapped[str | None] = mapped_column(String(255), nullable=True)
    # ``schedule`` lanes only; 5-field UTC cron (``schedule: "0 9 * * *"``).
    cron: Mapped[str | None] = mapped_column(String(128), nullable=True)
    # ``once`` lanes only; opaque string that callers compare against
    # a ledger so reseeds don't fire twice.
    idempotency_key: Mapped[str | None] = mapped_column(
        String(255), nullable=True
    )
    enabled: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default=text("true")
    )
    config_blob: Mapped[dict] = mapped_column(
        JSONB, nullable=False, server_default=text("'{}'::jsonb")
    )

    last_run_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )
    last_run_status: Mapped[str | None] = mapped_column(
        String(32), nullable=True
    )

    synced_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=text("now()"),
    )
    # ``<ref_sha>:<path>`` where we pulled the config from. Powers the
    # Console's freshness badge and lets the webhook reconciler skip
    # a fetch when the SHA matches.
    sync_source: Mapped[str | None] = mapped_column(String(255), nullable=True)

    created_at: Mapped[datetime] = _ts_created()
    updated_at: Mapped[datetime] = _ts_updated()

    workspace: Mapped[Workspace] = relationship()
    repo: Mapped[WorkspaceRepo] = relationship()


__all__ = ["Lane"]
