import Link from "next/link";
import { redirect } from "next/navigation";

import { AppShell } from "@/components/app-shell";
import {
  Badge,
  ButtonGhost,
  ButtonPrimary,
  Card,
  CardHeader,
  MockBanner,
  StatTile,
} from "@/components/ui";
import {
  ApiHttpError,
  ApiUnavailableError,
  isApiConfigured,
  listWorkspaces,
} from "@/lib/api/client";
import { getSessionToken } from "@/lib/api/session";
import {
  actionItems,
  kpis,
  recentRuns,
  relativeTime,
  workspaces,
  yesterdayDigest,
} from "@/lib/mock/cloud";

const ws = workspaces[0];

export const dynamic = "force-dynamic";

export default async function CloudHomePage() {
  // If the user is authed against a real backend but has zero workspaces,
  // bounce them into the onboarding wizard so the dashboard isn't a confusing
  // wall of mock data on first run.
  if (isApiConfigured()) {
    const token = await getSessionToken();
    if (token) {
      const result = await loadWorkspaces(token);
      if (result === "empty") redirect("/onboarding?step=repo");
      if (result === "unauthorized") redirect("/login");
      // "ok" or "down" → fall through to the dashboard (mock for now).
    }
  }

  return renderDashboard();
}

async function loadWorkspaces(
  token: string,
): Promise<"ok" | "empty" | "unauthorized" | "down"> {
  try {
    const list = await listWorkspaces(token);
    return list.length === 0 ? "empty" : "ok";
  } catch (err) {
    if (err instanceof ApiHttpError && err.status === 401) return "unauthorized";
    if (err instanceof ApiUnavailableError) return "down";
    return "down";
  }
}

function renderDashboard() {
  const proposed = actionItems.filter((a) => a.status === "proposed");
  const approved = actionItems.filter((a) => a.status === "approved");

  return (
    <AppShell
      kicker={ws.org}
      title="Operating dashboard"
      actions={
        <>
          <ButtonGhost>Export digest</ButtonGhost>
          <ButtonPrimary>+ Trigger lane</ButtonPrimary>
        </>
      }
    >
      <MockBanner />

      <section className="grid grid-cols-1 gap-4 sm:grid-cols-2 xl:grid-cols-4">
        {kpis.map((k) => (
          <StatTile key={k.label} {...k} />
        ))}
      </section>

      <section className="mt-8 grid grid-cols-1 gap-5 lg:grid-cols-3">
        {/* Yesterday's digest */}
        <Card className="lg:col-span-2">
          <CardHeader
            title="Yesterday's digest"
            subtitle={`Generated by daily lane · ${yesterdayDigest.date}`}
            action={
              <Link
                href="/daily"
                className="text-xs font-semibold text-aqua hover:underline"
              >
                Open →
              </Link>
            }
          />
          <p className="text-sm leading-relaxed text-white/80">{yesterdayDigest.summary}</p>
          <div className="mt-5 grid grid-cols-1 gap-4 md:grid-cols-3">
            <DigestColumn title="Shipped" tone="ok" items={yesterdayDigest.shipped} />
            <DigestColumn title="In flight" tone="info" items={yesterdayDigest.inFlight} />
            <DigestColumn title="Blockers" tone="err" items={yesterdayDigest.blockers} />
          </div>
        </Card>

        {/* Proposed action items */}
        <Card>
          <CardHeader
            title="Action items waiting"
            subtitle={`${proposed.length} proposed · ${approved.length} approved this week`}
            action={
              <Link
                href="/daily"
                className="text-xs font-semibold text-aqua hover:underline"
              >
                Triage →
              </Link>
            }
          />
          <ul className="space-y-3">
            {proposed.map((a) => (
              <li
                key={a.id}
                className="rounded-xl border border-white/10 bg-white/[0.03] p-3 transition hover:border-white/20"
              >
                <div className="flex items-start gap-2">
                  <Badge
                    tone={
                      a.severity === "high" ? "err" : a.severity === "med" ? "warn" : "info"
                    }
                  >
                    {a.severity}
                  </Badge>
                  <span className="text-[10px] uppercase tracking-widest text-white/40">
                    {a.source}
                  </span>
                </div>
                <h4 className="mt-1.5 text-sm font-semibold text-white">{a.title}</h4>
                <p className="mt-1 line-clamp-2 text-xs text-white/55">{a.reason}</p>
                <div className="mt-2 flex items-center gap-2">
                  <button className="rounded-full bg-emerald-400/15 px-2.5 py-1 text-[11px] font-bold text-emerald-300 hover:bg-emerald-400/25">
                    Approve → tracker
                  </button>
                  <button className="rounded-full border border-white/15 px-2.5 py-1 text-[11px] font-semibold text-white/65 hover:bg-white/[0.06] hover:text-white">
                    Reject
                  </button>
                </div>
              </li>
            ))}
          </ul>
        </Card>
      </section>

      <section className="mt-8 grid grid-cols-1 gap-5 lg:grid-cols-3">
        <Card className="lg:col-span-2">
          <CardHeader
            title="Recent lane runs"
            subtitle="Daily, retro, scheduled and self-heal lanes — last 24 hours"
            action={
              <Link
                href="/workflows"
                className="text-xs font-semibold text-aqua hover:underline"
              >
                All runs →
              </Link>
            }
          />
          <div className="overflow-hidden rounded-xl border border-white/10">
            <table className="min-w-full text-sm">
              <thead className="bg-white/[0.04] text-[10px] uppercase tracking-widest text-white/45">
                <tr>
                  <th className="px-3 py-2 text-left font-semibold">Lane</th>
                  <th className="px-3 py-2 text-left font-semibold">Status</th>
                  <th className="px-3 py-2 text-left font-semibold">When</th>
                  <th className="px-3 py-2 text-left font-semibold">Highlight</th>
                </tr>
              </thead>
              <tbody>
                {recentRuns.map((r) => (
                  <tr key={r.id} className="border-t border-white/5 hover:bg-white/[0.02]">
                    <td className="px-3 py-2.5 align-top">
                      <div className="font-semibold capitalize text-white">{r.kind}</div>
                      <div className="text-[10px] text-white/40">{r.trigger}</div>
                    </td>
                    <td className="px-3 py-2.5 align-top">
                      <Badge
                        tone={
                          r.status === "ok"
                            ? "ok"
                            : r.status === "warning"
                              ? "warn"
                              : "err"
                        }
                        dot
                      >
                        {r.status} · {Math.round(r.durationSec)}s
                      </Badge>
                    </td>
                    <td className="px-3 py-2.5 align-top text-xs text-white/55">
                      {relativeTime(r.startedAt)}
                    </td>
                    <td className="px-3 py-2.5 align-top text-xs text-white/75">
                      {r.highlight}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        </Card>

        <Card>
          <CardHeader title="Catalog sources" subtitle="Toggled per workspace" />
          <ul className="space-y-3">
            {(["global", "workspace", "project"] as const).map((src) => (
              <li
                key={src}
                className="flex items-center justify-between gap-3 rounded-lg border border-white/10 bg-white/[0.02] px-3 py-2.5"
              >
                <div className="min-w-0">
                  <div className="flex items-center gap-2">
                    <Badge
                      tone={src === "global" ? "neutral" : src === "workspace" ? "workspace" : "project"}
                    >
                      {src}
                    </Badge>
                  </div>
                  <p className="mt-1 text-[11px] leading-snug text-white/55">
                    {src === "global"
                      ? "Read-only mirror of the public Ship monorepo."
                      : src === "workspace"
                        ? "Helio · Platform team's private artifact repo."
                        : "Project-pinned overrides (e.g. Helio Payments)."}
                  </p>
                </div>
                <FakeToggle on={ws.catalogSources[src]} />
              </li>
            ))}
          </ul>
          <Link
            href="/settings"
            className="mt-4 block text-center text-xs font-semibold text-aqua hover:underline"
          >
            Manage in workspace settings →
          </Link>
        </Card>
      </section>
    </AppShell>
  );
}

function DigestColumn({
  title,
  tone,
  items,
}: {
  title: string;
  tone: "ok" | "info" | "err";
  items: string[];
}) {
  return (
    <div>
      <Badge tone={tone}>{title}</Badge>
      <ul className="mt-2 space-y-1.5">
        {items.map((item) => (
          <li
            key={item}
            className="flex gap-2 text-xs leading-snug text-white/75 before:content-['·'] before:text-white/30"
          >
            <span>{item}</span>
          </li>
        ))}
      </ul>
    </div>
  );
}

function FakeToggle({ on }: { on: boolean }) {
  return (
    <span
      aria-hidden
      className={
        "relative inline-flex h-5 w-9 shrink-0 items-center rounded-full transition " +
        (on ? "bg-aqua/70" : "bg-white/10")
      }
    >
      <span
        className={
          "inline-block h-4 w-4 transform rounded-full bg-white shadow transition " +
          (on ? "translate-x-4" : "translate-x-0.5")
        }
      />
    </span>
  );
}
