"""Lane config editor endpoints (Phase 2 of Lanes hub).

Covers ``GET /v1/workspaces/{ws}/repos/{repo_id}/config`` and
``POST /v1/workspaces/{ws}/repos/{repo_id}/config/propose``:

- ``GET`` fetches the live blob, returns ``(raw_yaml, parsed, sha)``
  and handles missing / unparseable config gracefully.
- ``POST`` validates the edited mapping, enforces optimistic locking
  against the vendor SHA, and opens a single-file PR via
  ``commit_bundle_pr``.

The GitHub integrations are all monkeypatched — no vendor calls from
tests. We mostly care about the 4xx/5xx surface + that the emitter
output lands in the PR as one file.
"""

from __future__ import annotations

from datetime import datetime, timezone

import pytest
import pytest_asyncio


@pytest_asyncio.fixture
async def seed_workspace_with_repo(db_session, seed_workspace):
    from backend.app.db.models.integrations import (
        GitHubInstallation,
        WorkspaceRepo,
    )

    _, raw, workspace = seed_workspace
    install = GitHubInstallation(
        workspace_id=workspace.id,
        installation_id=888_010,
        account_login="acme",
        account_type="Organization",
        repository_selection="selected",
        installed_at=datetime.now(timezone.utc),
    )
    db_session.add(install)
    await db_session.flush()

    repo = WorkspaceRepo(
        workspace_id=workspace.id,
        installation_id=install.id,
        provider="github",
        external_id=42_888_010,
        full_name="acme/lanes-config",
        default_branch="main",
        private=False,
        html_url="https://github.com/acme/lanes-config",
        activated_at=datetime.now(timezone.utc),
        preset="web-app",
    )
    db_session.add(repo)
    await db_session.flush()
    return raw, workspace, install, repo


def _patch_blob(monkeypatch, *, content: str, sha: str = "deadbeef"):
    """Stub ``GitHubCodeHost.get_blob`` to return a predictable blob."""
    from backend.app.integrations.gateway.code_host import BlobContent

    async def _get_blob(self, ref, *, path, ref_sha=None):
        return BlobContent(
            path=path,
            ref=ref_sha or "main",
            sha=sha,
            size=len(content.encode("utf-8")),
            encoding="utf-8",
            content=content,
        )

    monkeypatch.setattr(
        "backend.app.integrations.github.code_host_adapter."
        "GitHubCodeHost.get_blob",
        _get_blob,
    )


def _patch_blob_missing(monkeypatch):
    async def _get_blob(self, ref, *, path, ref_sha=None):
        raise FileNotFoundError(f"{ref.owner}/{ref.repo}:{path}")

    monkeypatch.setattr(
        "backend.app.integrations.github.code_host_adapter."
        "GitHubCodeHost.get_blob",
        _get_blob,
    )


_SAMPLE_CONFIG = (
    "# Generated by Ship — install bundle\n"
    "preset: web-app\n"
    "version: 2\n"
    "repo: acme/lanes-config\n"
    "lanes:\n"
    "  pr_review:\n"
    '    event: pull_request\n'
    '    pattern: "**"\n'
    '    idempotency_key: "{{pr}}"\n'
    "  daily_standup:\n"
    '    schedule: "0 9 * * 1-5"\n'
)


@pytest.mark.asyncio
async def test_read_config_returns_raw_parsed_and_sha(
    monkeypatch, v1_client, seed_workspace_with_repo
) -> None:
    raw, workspace, _install, repo = seed_workspace_with_repo
    _patch_blob(monkeypatch, content=_SAMPLE_CONFIG, sha="sha-abc")

    response = await v1_client.get(
        f"/v1/workspaces/{workspace.id}/repos/{repo.id}/config",
        headers={"Authorization": f"Bearer {raw}"},
    )
    assert response.status_code == 200, response.text
    body = response.json()
    assert body["exists"] is True
    assert body["sha"] == "sha-abc"
    assert body["raw_yaml"] == _SAMPLE_CONFIG
    assert body["parsed"]["preset"] == "web-app"
    assert "pr_review" in body["parsed"]["lanes"]
    assert body["parse_error"] is None


@pytest.mark.asyncio
async def test_read_config_missing_file_returns_exists_false(
    monkeypatch, v1_client, seed_workspace_with_repo
) -> None:
    raw, workspace, _install, repo = seed_workspace_with_repo
    _patch_blob_missing(monkeypatch)

    response = await v1_client.get(
        f"/v1/workspaces/{workspace.id}/repos/{repo.id}/config",
        headers={"Authorization": f"Bearer {raw}"},
    )
    assert response.status_code == 200, response.text
    body = response.json()
    assert body["exists"] is False
    assert body["sha"] is None
    assert body["raw_yaml"] is None


@pytest.mark.asyncio
async def test_read_config_unparseable_yaml_surfaces_parse_error(
    monkeypatch, v1_client, seed_workspace_with_repo
) -> None:
    raw, workspace, _install, repo = seed_workspace_with_repo
    _patch_blob(monkeypatch, content="lanes:\n  :\n  bad indent", sha="sha-x")

    response = await v1_client.get(
        f"/v1/workspaces/{workspace.id}/repos/{repo.id}/config",
        headers={"Authorization": f"Bearer {raw}"},
    )
    assert response.status_code == 200, response.text
    body = response.json()
    assert body["exists"] is True
    assert body["parsed"] is None
    assert body["parse_error"]


@pytest.mark.asyncio
async def test_propose_opens_single_file_pr(
    monkeypatch, v1_client, seed_workspace_with_repo
) -> None:
    from backend.app.integrations.github.workflows import StarterWorkflowPR

    raw, workspace, _install, repo = seed_workspace_with_repo
    _patch_blob(monkeypatch, content=_SAMPLE_CONFIG, sha="sha-abc")

    captured: dict[str, object] = {}

    async def _commit(
        repo, install, *, files, title, branch_label, pr_body_header, settings,
        return_url=None, client=None,
    ):
        captured["files"] = files
        captured["title"] = title
        captured["branch_label"] = branch_label
        return StarterWorkflowPR(
            pr_url="https://github.com/acme/lanes-config/pull/7",
            pr_number=7,
            branch="ship/lanes-config-123",
        )

    monkeypatch.setattr(
        "backend.app.integrations.github.workflows.commit_bundle_pr", _commit
    )

    response = await v1_client.post(
        f"/v1/workspaces/{workspace.id}/repos/{repo.id}/config/propose",
        headers={"Authorization": f"Bearer {raw}"},
        json={
            "base_sha": "sha-abc",
            "change_summary": "Pause the weekly tech-debt lane",
            "lanes": {
                "pr_review": {
                    "event": "pull_request",
                    "pattern": "**",
                    "idempotency_key": "{{pr}}",
                },
                "daily_standup": {"schedule": "0 9 * * 1-5"},
            },
        },
    )
    assert response.status_code == 200, response.text
    body = response.json()
    assert body["pr_number"] == 7

    # PR carries exactly one file (.ship/config.yml) and it contains
    # the emitter's canonical output, not arbitrary user bytes.
    files = captured["files"]
    assert isinstance(files, list) and len(files) == 1
    path, content = files[0]
    assert path == ".ship/config.yml"
    assert "preset: web-app" in content
    assert "pr_review:" in content
    assert "daily_standup:" in content


@pytest.mark.asyncio
async def test_propose_rejects_sha_mismatch_with_409(
    monkeypatch, v1_client, seed_workspace_with_repo
) -> None:
    raw, workspace, _install, repo = seed_workspace_with_repo
    _patch_blob(monkeypatch, content=_SAMPLE_CONFIG, sha="new-sha")

    response = await v1_client.post(
        f"/v1/workspaces/{workspace.id}/repos/{repo.id}/config/propose",
        headers={"Authorization": f"Bearer {raw}"},
        json={
            "base_sha": "stale-sha",
            "lanes": {"pr_review": {"event": "pull_request"}},
        },
    )
    assert response.status_code == 409, response.text
    detail = response.json()["detail"]
    assert detail["code"] == "sha_mismatch"
    assert detail["current_sha"] == "new-sha"


@pytest.mark.asyncio
async def test_propose_rejects_invalid_trigger(
    monkeypatch, v1_client, seed_workspace_with_repo
) -> None:
    raw, workspace, _install, repo = seed_workspace_with_repo
    _patch_blob(monkeypatch, content=_SAMPLE_CONFIG, sha="sha-abc")

    response = await v1_client.post(
        f"/v1/workspaces/{workspace.id}/repos/{repo.id}/config/propose",
        headers={"Authorization": f"Bearer {raw}"},
        json={
            "base_sha": "sha-abc",
            "lanes": {
                "broken": {
                    "event": "pull_request",
                    "schedule": "0 9 * * *",
                },
            },
        },
    )
    assert response.status_code == 422, response.text
    assert response.json()["detail"]["code"] == "invalid_trigger"


@pytest.mark.asyncio
async def test_propose_rejects_empty_lanes(
    monkeypatch, v1_client, seed_workspace_with_repo
) -> None:
    raw, workspace, _install, repo = seed_workspace_with_repo
    _patch_blob(monkeypatch, content=_SAMPLE_CONFIG, sha="sha-abc")

    response = await v1_client.post(
        f"/v1/workspaces/{workspace.id}/repos/{repo.id}/config/propose",
        headers={"Authorization": f"Bearer {raw}"},
        json={"base_sha": "sha-abc", "lanes": {}},
    )
    assert response.status_code == 422, response.text
    assert response.json()["detail"]["code"] == "empty_lanes"


@pytest.mark.asyncio
async def test_propose_emits_process_agent_profile(
    monkeypatch, v1_client, seed_workspace_with_repo
) -> None:
    from backend.app.integrations.github.workflows import StarterWorkflowPR

    raw, workspace, _install, repo = seed_workspace_with_repo
    _patch_blob(monkeypatch, content=_SAMPLE_CONFIG, sha="sha-abc")
    captured: dict[str, object] = {}

    async def _commit(
        repo, install, *, files, title, branch_label, pr_body_header, settings,
        return_url=None, client=None,
    ):
        captured["files"] = files
        return StarterWorkflowPR(
            pr_url="https://github.com/acme/lanes-config/pull/13",
            pr_number=13,
            branch="ship/process-agent-profile",
        )

    monkeypatch.setattr(
        "backend.app.integrations.github.workflows.commit_bundle_pr", _commit
    )

    response = await v1_client.post(
        f"/v1/workspaces/{workspace.id}/repos/{repo.id}/config/propose",
        headers={"Authorization": f"Bearer {raw}"},
        json={
            "base_sha": "sha-abc",
            "lanes": {},
            "process": {
                "id": "development",
                "name": "Development Process",
                "primary": True,
                "states": [
                    {
                        "id": "implementation",
                        "name": "Implementation",
                        "specialist": {
                            "id": "developer",
                            "name": "Developer",
                            "agent_profile": "cursor_agent",
                        },
                    }
                ],
                "transitions": [],
            },
        },
    )

    assert response.status_code == 200, response.text
    files = captured["files"]
    assert isinstance(files, list) and len(files) == 1
    _, content = files[0]
    assert "process:" in content
    assert "agent_profile: cursor_agent" in content


@pytest.mark.asyncio
async def test_propose_rejects_unknown_process_agent_profile(
    v1_client, seed_workspace_with_repo
) -> None:
    raw, workspace, _install, repo = seed_workspace_with_repo

    response = await v1_client.post(
        f"/v1/workspaces/{workspace.id}/repos/{repo.id}/config/propose",
        headers={"Authorization": f"Bearer {raw}"},
        json={
            "base_sha": "sha-abc",
            "lanes": {},
            "process": {
                "id": "development",
                "name": "Development Process",
                "primary": True,
                "states": [
                    {
                        "id": "implementation",
                        "name": "Implementation",
                        "specialist": {
                            "id": "developer",
                            "name": "Developer",
                            "agent_profile": "teleport",
                        },
                    }
                ],
            },
        },
    )

    assert response.status_code == 422, response.text
    detail = response.json()["detail"]
    assert detail["code"] == "invalid_process"
    assert "specialist.agent_profile" in detail["message"]


# ---------------------------------------------------------------------------
# RFC-0008 C3.1 — ``patterns: [ids]`` on POST /config/propose
# ---------------------------------------------------------------------------


@pytest.mark.asyncio
async def test_propose_emits_patterns_list_for_multi_pattern_lane(
    monkeypatch, v1_client, seed_workspace_with_repo
) -> None:
    """Multi-pattern lanes round-trip through the emitter as a flow list.

    Single-pattern lanes keep the compact ``pattern: <id>`` shape so
    existing configs see no diff; only lanes that genuinely have more
    than one pattern upgrade to ``patterns: [a, b, c]``.
    """
    from backend.app.integrations.github.workflows import StarterWorkflowPR

    raw, workspace, _install, repo = seed_workspace_with_repo
    _patch_blob(monkeypatch, content=_SAMPLE_CONFIG, sha="sha-abc")

    captured: dict[str, object] = {}

    async def _commit(
        repo, install, *, files, title, branch_label, pr_body_header, settings,
        return_url=None, client=None,
    ):
        captured["files"] = files
        return StarterWorkflowPR(
            pr_url="https://github.com/acme/lanes-config/pull/9",
            pr_number=9,
            branch="ship/lanes-config-multi",
        )

    monkeypatch.setattr(
        "backend.app.integrations.github.workflows.commit_bundle_pr", _commit
    )

    response = await v1_client.post(
        f"/v1/workspaces/{workspace.id}/repos/{repo.id}/config/propose",
        headers={"Authorization": f"Bearer {raw}"},
        json={
            "base_sha": "sha-abc",
            "change_summary": "Audit lane now fans out to three roles",
            "lanes": {
                "tech_debt_audit": {
                    "schedule": "0 6 * * 1",
                    "patterns": [
                        "role-tech-architect",
                        "role-qa-architect",
                        "role-security-officer",
                    ],
                },
                # Single-pattern lane stays on the scalar alias so the
                # diff against the previous config is minimal.
                "pr_review": {
                    "event": "pull_request",
                    "pattern": "flow-pr-self-review",
                },
            },
        },
    )
    assert response.status_code == 200, response.text

    files = captured["files"]
    assert len(files) == 1
    _, content = files[0]
    # Multi-pattern lane → inline flow list, alphabetic-preserving order.
    assert (
        "patterns: [role-tech-architect, role-qa-architect, role-security-officer]"
        in content
    )
    # Single-pattern lane stays on ``pattern:`` scalar.
    assert "pattern: flow-pr-self-review" in content
    # And the old scalar form didn't leak into the multi lane.
    assert "pattern: role-tech-architect" not in content


@pytest.mark.asyncio
async def test_propose_rejects_patterns_and_pattern_together(
    monkeypatch, v1_client, seed_workspace_with_repo
) -> None:
    raw, workspace, _install, repo = seed_workspace_with_repo
    _patch_blob(monkeypatch, content=_SAMPLE_CONFIG, sha="sha-abc")

    response = await v1_client.post(
        f"/v1/workspaces/{workspace.id}/repos/{repo.id}/config/propose",
        headers={"Authorization": f"Bearer {raw}"},
        json={
            "base_sha": "sha-abc",
            "lanes": {
                "confused": {
                    "event": "pull_request",
                    "pattern": "flow-pr-self-review",
                    "patterns": ["flow-pr-self-review"],
                },
            },
        },
    )
    assert response.status_code == 422, response.text
    assert response.json()["detail"]["code"] == "invalid_pattern_shape"


@pytest.mark.asyncio
async def test_propose_emits_fanout_only_for_multi_pattern_lanes(
    monkeypatch, v1_client, seed_workspace_with_repo
) -> None:
    """`fanout` is only useful when ≥2 patterns fan out together.

    For single-pattern lanes (even when the caller sent fanout) the
    emitter drops the key so we don't pollute diffs with fields that
    have no runtime effect. For multi-pattern lanes ``matrix``
    (default) is also omitted; ``sequential`` / ``concurrent`` are
    written through.
    """
    from backend.app.integrations.github.workflows import StarterWorkflowPR

    raw, workspace, _install, repo = seed_workspace_with_repo
    _patch_blob(monkeypatch, content=_SAMPLE_CONFIG, sha="sha-abc")

    captured: dict[str, object] = {}

    async def _commit(
        repo, install, *, files, title, branch_label, pr_body_header, settings,
        return_url=None, client=None,
    ):
        captured["files"] = files
        return StarterWorkflowPR(
            pr_url="https://github.com/acme/lanes-config/pull/11",
            pr_number=11,
            branch="ship/lanes-fanout",
        )

    monkeypatch.setattr(
        "backend.app.integrations.github.workflows.commit_bundle_pr", _commit
    )

    response = await v1_client.post(
        f"/v1/workspaces/{workspace.id}/repos/{repo.id}/config/propose",
        headers={"Authorization": f"Bearer {raw}"},
        json={
            "base_sha": "sha-abc",
            "change_summary": "Pick sequential fanout for the audit lane",
            "lanes": {
                # Single-pattern lane: fanout is not emitted even if
                # the caller sent it — it has no runtime effect.
                "pr_review": {
                    "event": "pull_request",
                    "pattern": "flow-pr-self-review",
                    "fanout": "sequential",
                },
                # Multi-pattern lane with default fanout=matrix: key
                # omitted (matrix is the runtime default, no diff).
                "tech_debt_default": {
                    "schedule": "0 6 * * 1",
                    "patterns": ["role-tech-architect", "role-qa-architect"],
                    "fanout": "matrix",
                },
                # Multi-pattern with an explicit non-default fanout:
                # the key lands in the YAML so the CLI honours it.
                "tech_debt_seq": {
                    "schedule": "0 7 * * 1",
                    "patterns": [
                        "role-tech-architect",
                        "role-qa-architect",
                        "role-security-officer",
                    ],
                    "fanout": "sequential",
                },
            },
        },
    )
    assert response.status_code == 200, response.text

    files = captured["files"]
    _, content = files[0]
    # pr_review: single-pattern → no fanout key anywhere near it.
    pr_block = content.split("pr_review:")[1].split("tech_debt_default")[0]
    assert "fanout" not in pr_block
    # tech_debt_default: multi-pattern but matrix is the default → still no fanout.
    td_default = content.split("tech_debt_default:")[1].split("tech_debt_seq")[0]
    assert "fanout" not in td_default
    # tech_debt_seq: explicit non-default → key is written.
    td_seq = content.split("tech_debt_seq:")[1]
    assert "fanout: sequential" in td_seq


@pytest.mark.asyncio
async def test_propose_rejects_unknown_fanout(
    monkeypatch, v1_client, seed_workspace_with_repo
) -> None:
    raw, workspace, _install, repo = seed_workspace_with_repo
    _patch_blob(monkeypatch, content=_SAMPLE_CONFIG, sha="sha-abc")

    response = await v1_client.post(
        f"/v1/workspaces/{workspace.id}/repos/{repo.id}/config/propose",
        headers={"Authorization": f"Bearer {raw}"},
        json={
            "base_sha": "sha-abc",
            "lanes": {
                "audit": {
                    "schedule": "0 6 * * 1",
                    "patterns": ["role-tech-architect", "role-qa-architect"],
                    "fanout": "teleport",
                },
            },
        },
    )
    assert response.status_code == 422, response.text
    assert response.json()["detail"]["code"] == "invalid_fanout"


@pytest.mark.asyncio
async def test_propose_rejects_empty_patterns_list(
    monkeypatch, v1_client, seed_workspace_with_repo
) -> None:
    raw, workspace, _install, repo = seed_workspace_with_repo
    _patch_blob(monkeypatch, content=_SAMPLE_CONFIG, sha="sha-abc")

    response = await v1_client.post(
        f"/v1/workspaces/{workspace.id}/repos/{repo.id}/config/propose",
        headers={"Authorization": f"Bearer {raw}"},
        json={
            "base_sha": "sha-abc",
            "lanes": {
                "empty": {"schedule": "0 9 * * *", "patterns": []},
            },
        },
    )
    assert response.status_code == 422, response.text
    assert response.json()["detail"]["code"] == "invalid_patterns"
