"""Lane config editor endpoints (Phase 2 of Lanes hub).

Covers ``GET /v1/workspaces/{ws}/repos/{repo_id}/config`` and
``POST /v1/workspaces/{ws}/repos/{repo_id}/config/propose``:

- ``GET`` fetches the live blob, returns ``(raw_yaml, parsed, sha)``
  and handles missing / unparseable config gracefully.
- ``POST`` validates the edited mapping, enforces optimistic locking
  against the vendor SHA, and opens a single-file PR via
  ``commit_bundle_pr``.

The GitHub integrations are all monkeypatched — no vendor calls from
tests. We mostly care about the 4xx/5xx surface + that the emitter
output lands in the PR as one file.
"""

from __future__ import annotations

from datetime import datetime, timezone

import pytest
import pytest_asyncio


@pytest_asyncio.fixture
async def seed_workspace_with_repo(db_session, seed_workspace):
    from backend.app.db.models.integrations import (
        GitHubInstallation,
        WorkspaceRepo,
    )

    _, raw, workspace = seed_workspace
    install = GitHubInstallation(
        workspace_id=workspace.id,
        installation_id=888_010,
        account_login="acme",
        account_type="Organization",
        repository_selection="selected",
        installed_at=datetime.now(timezone.utc),
    )
    db_session.add(install)
    await db_session.flush()

    repo = WorkspaceRepo(
        workspace_id=workspace.id,
        installation_id=install.id,
        provider="github",
        external_id=42_888_010,
        full_name="acme/lanes-config",
        default_branch="main",
        private=False,
        html_url="https://github.com/acme/lanes-config",
        activated_at=datetime.now(timezone.utc),
        preset="web-app",
    )
    db_session.add(repo)
    await db_session.flush()
    return raw, workspace, install, repo


def _patch_blob(monkeypatch, *, content: str, sha: str = "deadbeef"):
    """Stub ``GitHubCodeHost.get_blob`` to return a predictable blob."""
    from backend.app.integrations.gateway.code_host import BlobContent

    async def _get_blob(self, ref, *, path, ref_sha=None):
        return BlobContent(
            path=path,
            ref=ref_sha or "main",
            sha=sha,
            size=len(content.encode("utf-8")),
            encoding="utf-8",
            content=content,
        )

    monkeypatch.setattr(
        "backend.app.integrations.github.code_host_adapter."
        "GitHubCodeHost.get_blob",
        _get_blob,
    )


def _patch_blob_missing(monkeypatch):
    async def _get_blob(self, ref, *, path, ref_sha=None):
        raise FileNotFoundError(f"{ref.owner}/{ref.repo}:{path}")

    monkeypatch.setattr(
        "backend.app.integrations.github.code_host_adapter."
        "GitHubCodeHost.get_blob",
        _get_blob,
    )


_SAMPLE_CONFIG = (
    "# Generated by Ship — install bundle\n"
    "preset: web-app\n"
    "version: 2\n"
    "repo: acme/lanes-config\n"
    "lanes:\n"
    "  pr_review:\n"
    '    event: pull_request\n'
    '    pattern: "**"\n'
    '    idempotency_key: "{{pr}}"\n'
    "  daily_standup:\n"
    '    schedule: "0 9 * * 1-5"\n'
)


@pytest.mark.asyncio
async def test_read_config_returns_raw_parsed_and_sha(
    monkeypatch, v1_client, seed_workspace_with_repo
) -> None:
    raw, workspace, _install, repo = seed_workspace_with_repo
    _patch_blob(monkeypatch, content=_SAMPLE_CONFIG, sha="sha-abc")

    response = await v1_client.get(
        f"/v1/workspaces/{workspace.id}/repos/{repo.id}/config",
        headers={"Authorization": f"Bearer {raw}"},
    )
    assert response.status_code == 200, response.text
    body = response.json()
    assert body["exists"] is True
    assert body["sha"] == "sha-abc"
    assert body["raw_yaml"] == _SAMPLE_CONFIG
    assert body["parsed"]["preset"] == "web-app"
    assert "pr_review" in body["parsed"]["lanes"]
    assert body["parse_error"] is None


@pytest.mark.asyncio
async def test_read_config_missing_file_returns_exists_false(
    monkeypatch, v1_client, seed_workspace_with_repo
) -> None:
    raw, workspace, _install, repo = seed_workspace_with_repo
    _patch_blob_missing(monkeypatch)

    response = await v1_client.get(
        f"/v1/workspaces/{workspace.id}/repos/{repo.id}/config",
        headers={"Authorization": f"Bearer {raw}"},
    )
    assert response.status_code == 200, response.text
    body = response.json()
    assert body["exists"] is False
    assert body["sha"] is None
    assert body["raw_yaml"] is None


@pytest.mark.asyncio
async def test_read_config_unparseable_yaml_surfaces_parse_error(
    monkeypatch, v1_client, seed_workspace_with_repo
) -> None:
    raw, workspace, _install, repo = seed_workspace_with_repo
    _patch_blob(monkeypatch, content="lanes:\n  :\n  bad indent", sha="sha-x")

    response = await v1_client.get(
        f"/v1/workspaces/{workspace.id}/repos/{repo.id}/config",
        headers={"Authorization": f"Bearer {raw}"},
    )
    assert response.status_code == 200, response.text
    body = response.json()
    assert body["exists"] is True
    assert body["parsed"] is None
    assert body["parse_error"]


@pytest.mark.asyncio
async def test_propose_opens_single_file_pr(
    monkeypatch, v1_client, seed_workspace_with_repo
) -> None:
    from backend.app.integrations.github.workflows import StarterWorkflowPR

    raw, workspace, _install, repo = seed_workspace_with_repo
    _patch_blob(monkeypatch, content=_SAMPLE_CONFIG, sha="sha-abc")

    captured: dict[str, object] = {}

    async def _commit(
        repo, install, *, files, title, branch_label, pr_body_header, settings,
        return_url=None, client=None,
    ):
        captured["files"] = files
        captured["title"] = title
        captured["branch_label"] = branch_label
        return StarterWorkflowPR(
            pr_url="https://github.com/acme/lanes-config/pull/7",
            pr_number=7,
            branch="ship/lanes-config-123",
        )

    monkeypatch.setattr(
        "backend.app.integrations.github.workflows.commit_bundle_pr", _commit
    )

    response = await v1_client.post(
        f"/v1/workspaces/{workspace.id}/repos/{repo.id}/config/propose",
        headers={"Authorization": f"Bearer {raw}"},
        json={
            "base_sha": "sha-abc",
            "change_summary": "Pause the weekly tech-debt lane",
            "lanes": {
                "pr_review": {
                    "event": "pull_request",
                    "pattern": "**",
                    "idempotency_key": "{{pr}}",
                },
                "daily_standup": {"schedule": "0 9 * * 1-5"},
            },
        },
    )
    assert response.status_code == 200, response.text
    body = response.json()
    assert body["pr_number"] == 7

    # PR carries exactly one file (.ship/config.yml) and it contains
    # the emitter's canonical output, not arbitrary user bytes.
    files = captured["files"]
    assert isinstance(files, list) and len(files) == 1
    path, content = files[0]
    assert path == ".ship/config.yml"
    assert "preset: web-app" in content
    assert "pr_review:" in content
    assert "daily_standup:" in content


@pytest.mark.asyncio
async def test_propose_rejects_sha_mismatch_with_409(
    monkeypatch, v1_client, seed_workspace_with_repo
) -> None:
    raw, workspace, _install, repo = seed_workspace_with_repo
    _patch_blob(monkeypatch, content=_SAMPLE_CONFIG, sha="new-sha")

    response = await v1_client.post(
        f"/v1/workspaces/{workspace.id}/repos/{repo.id}/config/propose",
        headers={"Authorization": f"Bearer {raw}"},
        json={
            "base_sha": "stale-sha",
            "lanes": {"pr_review": {"event": "pull_request"}},
        },
    )
    assert response.status_code == 409, response.text
    detail = response.json()["detail"]
    assert detail["code"] == "sha_mismatch"
    assert detail["current_sha"] == "new-sha"


@pytest.mark.asyncio
async def test_propose_rejects_invalid_trigger(
    monkeypatch, v1_client, seed_workspace_with_repo
) -> None:
    raw, workspace, _install, repo = seed_workspace_with_repo
    _patch_blob(monkeypatch, content=_SAMPLE_CONFIG, sha="sha-abc")

    response = await v1_client.post(
        f"/v1/workspaces/{workspace.id}/repos/{repo.id}/config/propose",
        headers={"Authorization": f"Bearer {raw}"},
        json={
            "base_sha": "sha-abc",
            "lanes": {
                "broken": {
                    "event": "pull_request",
                    "schedule": "0 9 * * *",
                },
            },
        },
    )
    assert response.status_code == 422, response.text
    assert response.json()["detail"]["code"] == "invalid_trigger"


@pytest.mark.asyncio
async def test_propose_rejects_empty_lanes(
    monkeypatch, v1_client, seed_workspace_with_repo
) -> None:
    raw, workspace, _install, repo = seed_workspace_with_repo
    _patch_blob(monkeypatch, content=_SAMPLE_CONFIG, sha="sha-abc")

    response = await v1_client.post(
        f"/v1/workspaces/{workspace.id}/repos/{repo.id}/config/propose",
        headers={"Authorization": f"Bearer {raw}"},
        json={"base_sha": "sha-abc", "lanes": {}},
    )
    assert response.status_code == 422, response.text
    assert response.json()["detail"]["code"] == "empty_lanes"
