"""Deterministic generated knowledge docs for post-merge bootstrap."""

from __future__ import annotations

from typing import Any

from backend.app.db.models.integrations import WorkspaceRepo
from backend.app.db.models.repo_intel import RepoIntel


def render_generated_knowledge_files(
    *, repo: WorkspaceRepo, intel: RepoIntel
) -> list[tuple[str, str]]:
    """Return reviewable ``.ship/knowledge`` files for a merged repo."""

    return [
        (
            ".ship/knowledge/code-style.md",
            _render_code_style(repo=repo, intel=intel),
        ),
        (
            ".ship/knowledge/ui-runbook.md",
            _render_ui_runbook(repo=repo, intel=intel),
        ),
        (
            ".ship/knowledge/repo-architecture.md",
            _render_architecture(repo=repo, intel=intel),
        ),
        (
            ".ship/knowledge/dev-environment.md",
            _render_dev_environment(repo=repo, intel=intel),
        ),
    ]


def _header(title: str, *, repo: WorkspaceRepo, intel: RepoIntel) -> list[str]:
    return [
        f"# {title}",
        "",
        f"- Repo: `{repo.full_name}`",
        f"- Generated from repo intel version: {intel.version}",
        "",
        "> Generated by Ship after the wizard seed PR was merged. Review and edit this file before merging.",
        "",
    ]


def _render_code_style(*, repo: WorkspaceRepo, intel: RepoIntel) -> str:
    lines = _header("Code Style", repo=repo, intel=intel)
    lines.append("## Detected Stack")
    _append_list(lines, "Languages", _languages(intel.languages))
    _append_list(lines, "Frameworks", [str(v) for v in intel.frameworks or []])
    _append_list(lines, "Package managers", [str(v) for v in intel.package_managers or []])
    lines.append("## Commit Style")
    commit_style = intel.commit_style or {}
    lines.append(f"- Convention: `{commit_style.get('convention', 'unknown')}`")
    common = commit_style.get("common_types") or []
    if common:
        lines.append("- Common prefixes: " + ", ".join(f"`{item}`" for item in common))
    lines.append("")
    lines.append("## Review Guidance")
    lines.append("- Follow existing local patterns before introducing abstractions.")
    lines.append("- Keep changes scoped to the touched package/module.")
    lines.append("- Prefer commands and package managers already present in the repo.")
    return _finish(lines)


def _render_ui_runbook(*, repo: WorkspaceRepo, intel: RepoIntel) -> str:
    lines = _header("UI Runbook", repo=repo, intel=intel)
    tokens = intel.visual_tokens or {}
    if tokens:
        lines.append("## Visual Tokens")
        for key, value in tokens.items():
            lines.append(f"- {key}: `{value}`")
        lines.append("")
    else:
        lines.append("No visual token files were detected during bootstrap.")
        lines.append("")
    if "tailwindcss" in {str(v).lower() for v in intel.frameworks or []}:
        lines.append("## Tailwind")
        lines.append("- Tailwind appears to be part of this repo; prefer existing utility conventions.")
        lines.append("")
    lines.append("## Validation")
    lines.append("- For design changes, review the affected UI in a browser.")
    lines.append("- Preserve existing loading, empty, and error states.")
    return _finish(lines)


def _render_architecture(*, repo: WorkspaceRepo, intel: RepoIntel) -> str:
    lines = _header("Repository Architecture", repo=repo, intel=intel)
    structure = intel.structure or {}
    top_dirs = structure.get("top_level_dirs") or []
    if top_dirs:
        lines.append("## Top-level Directories")
        for dirname in top_dirs:
            lines.append(f"- `{dirname}`")
        lines.append("")
    if intel.entry_points:
        lines.append("## Entry Points")
        for entry in intel.entry_points:
            if isinstance(entry, dict):
                lines.append(f"- `{entry.get('path')}` ({entry.get('kind', 'unknown')})")
        lines.append("")
    if "file_count" in structure:
        lines.append(f"- File count: {structure['file_count']}")
    if "depth_p50" in structure:
        lines.append(f"- Depth p50/p95: {structure.get('depth_p50')}/{structure.get('depth_p95')}")
    return _finish(lines)


def _render_dev_environment(*, repo: WorkspaceRepo, intel: RepoIntel) -> str:
    lines = _header("Development Environment", repo=repo, intel=intel)
    _append_list(lines, "Package managers", [str(v) for v in intel.package_managers or []])
    if intel.entry_points:
        lines.append("## Useful Starting Points")
        for entry in intel.entry_points:
            if isinstance(entry, dict):
                lines.append(f"- `{entry.get('path')}` ({entry.get('kind', 'unknown')})")
        lines.append("")
    lines.append("## Suggested Command Discovery")
    lines.append("- Check package scripts, Makefile targets, or framework CLIs before guessing commands.")
    lines.append("- Prefer the repository's own CI workflow commands for validation.")
    return _finish(lines)


def _append_list(lines: list[str], title: str, values: list[str]) -> None:
    if not values:
        return
    lines.append(f"## {title}")
    for value in values:
        lines.append(f"- {value}")
    lines.append("")


def _languages(value: dict[str, Any] | None) -> list[str]:
    if not value:
        return []
    out: list[str] = []
    for name, ratio in value.items():
        try:
            pct = float(ratio) * 100
        except (TypeError, ValueError):
            continue
        out.append(f"`{name}`: {pct:.1f}%")
    return out


def _finish(lines: list[str]) -> str:
    return "\n".join(lines).rstrip() + "\n"


__all__ = ["render_generated_knowledge_files"]
