const MARKER = "<!-- ship-cli: methodology-api -->";

/**
 * @param {string} baseUrl
 */
export function cursorRuleMdc(baseUrl) {
  return `---
name: ship-methodology-api
description: Call the Ship methodology HTTP API (semantic search, fetch full docs, retro feedback, pattern index) from the agent.
---

${MARKER}

# Ship methodology API (local)

Base URL (override with \`SHIP_API_BASE\` for agents, or \`--base-url\` for CLI): \`${baseUrl}\`

## When to use

1. **Discover** — \`POST /search\` with a natural-language query over Ship docs + prompts.
2. **Read** — \`POST /fetch\` with a repo-relative \`path\` from search hits (markdown/text only).
3. **Retro** — \`POST /feedback\` to open a sanitized GitHub issue (needs \`GITHUB_TOKEN\` on the server).
4. **Catalog** — \`ship pattern|tool|workflow|collection list\` / \`show <id>\` / \`fetch <id>\` (\`GET /…\` on the same base URL as search, or \`POST /fetch\` with \`{ kind, id }\` when hosted; or disk when cwd/\`SHIP_REPO\` is the Ship tree).

## Examples (CLI from Ship repo)

\`\`\`bash
npm run ship -- search "release gates and qa split" --top-k 8
npm run ship -- docs fetch documentation/adoption/delivery-quality-and-release-process.md
npm run ship -- pattern list
\`\`\`

Equivalent curl (when not using the CLI):

\`\`\`bash
curl -sS -X POST "${baseUrl}/search" -H "Content-Type: application/json" \\
  -d '{"query":"release gates and qa split","top_k":8}'
curl -sS -X POST "${baseUrl}/fetch" -H "Content-Type: application/json" \\
  -d '{"path":"documentation/adoption/delivery-quality-and-release-process.md"}'
curl -sS "${baseUrl}/patterns"
\`\`\`

## Agent workflow

Prefer **search → fetch one path → quote** in your reply. Never paste secrets into \`/feedback\`; the server redacts common token shapes.

Run the API locally: \`uvicorn backend.app.main:app --reload --host 127.0.0.1 --port 8100\` (see \`documentation/tools/backend-api.md\` in the Ship repo).
`;
}

/**
 * @param {string} baseUrl
 */
export function markdownSection(baseUrl) {
  return `

---

${MARKER}

## Ship methodology API

Base URL: \`${baseUrl}\` (env \`SHIP_API_BASE\`).

- **Search** \`POST /search\` JSON \`{ "query": string, "top_k"?: number }\`
- **Fetch** \`POST /fetch\` JSON \`{ "path": "documentation/...md" }\`
- **Feedback** \`POST /feedback\` JSON \`{ "title", "summary", "recommendations"?: string[], "source_context"?: string }\`
- **Catalog** — \`ship pattern|tool|workflow|collection list\` / \`show <id>\` / \`fetch <id>\` (same \`SHIP_API_BASE\` as search, or local tree): \`GET /patterns\`, \`GET /patterns/{id}\`, or \`POST /fetch\` with \`{ "kind": "pattern", "id": "…" }\`

Use search first, then fetch the best path. Keep tokens out of feedback bodies.
`;
}

/**
 * @param {string} baseUrl
 */
export function standaloneDoc(baseUrl) {
  return `# Ship methodology API — agent reference

${MARKER}

Generated by \`ship init\`. Base URL: \`${baseUrl}\`

See the Ship repo \`documentation/tools/backend-api.md\` for full contract.

## Endpoints

| Method | Path | Body / notes |
|--------|------|----------------|
| POST | /search | \`{ "query": "...", "top_k": 8 }\` |
| POST | /fetch | \`{ "path": "documentation/foo.md" }\` |
| POST | /feedback | \`{ "title", "summary", "recommendations": [], "source_context" }\` |
| GET | /patterns | list manifest — **CLI:** \`ship pattern list\` (HTTP or disk in clone) |
| GET | /patterns/{id} | metadata + markdown \`content\` — **CLI:** \`ship pattern show <id>\` |
| POST | /fetch | catalog body — **CLI:** \`ship pattern fetch <id>\` with \`{ "kind": "pattern", "id" }\` |

## CLI (from Ship monorepo)

\`\`\`bash
npm run ship -- pattern list
npm run ship -- pattern show catalog-a1-intake
npm run ship -- search "intake labels" --top-k 5
\`\`\`

## curl (direct HTTP)

\`\`\`bash
export SHIP=${baseUrl}
curl -sS -X POST "$SHIP/search" -H "Content-Type: application/json" -d '{"query":"intake labels","top_k":5}'
\`\`\`
`;
}

export { MARKER };
