const MARKER = "<!-- ship-cli: artifacts-protocol v1 -->";
const END_MARKER = "<!-- ship-cli:end artifacts-protocol -->";

/**
 * Short "Artifacts protocol" stub shared by every rendered template.
 * Keep it tight; the authoritative contract lives in RFC-0001.
 *
 * @param {string} baseUrl
 */
function protocolBody(baseUrl) {
  return `Base URL (env \`SHIP_API_BASE\`, flag \`--base-url\`): \`${baseUrl}\`

## Artifacts protocol (RFC-0001)

Every Ship artifact is versioned (semver + \`content_sha256\`). Clients never
vendor artifact bodies — they call \`shipctl\` (which hits \`POST /fetch\` and
writes a local \`.ship/cache/<kind>/<id>@<version>/ARTIFACT.md\` entry).

Agent protocol (must follow before applying an artifact):

1. **Resolve before use.** Run \`shipctl <kind> show <id>\` (or \`fetch\`) so the
   body you act on is the current pinned version. Pins live in
   \`.ship/config.yml\` (\`artifacts.pins\`).
2. **Record the exact version.** Put \`<kind>:<id>@<version>\` in the PR
   description for every artifact you consumed (one per line).
3. **Do not copy bodies into the repo.** Reference the artifact id + version.
4. **Feedback is opt-in.** Use \`shipctl feedback draft\`; never auto-submit.

## CLI

\`\`\`bash
shipctl pattern list
shipctl pattern show cloud-developer              # resolves latest or pin
shipctl pattern fetch cloud-developer --version 1.4.2
shipctl search "release gates and qa split" --top-k 8
shipctl docs fetch documentation/adoption/delivery-quality-and-release-process.md
shipctl sync                                       # reconcile .ship/cache/
\`\`\`

## HTTP (curl, no CLI)

\`\`\`bash
curl -sS -X POST "${baseUrl}/fetch" -H "Content-Type: application/json" \\
  -d '{"kind":"pattern","id":"cloud-developer"}'
curl -sS "${baseUrl}/patterns"
\`\`\`

See \`documentation/protocol/rfc-0001-artifacts-protocol.md\` in the Ship repo for the
full HTTP surface, pin rules, and cache layout. \`.ship/config.yml\` schema is
RFC-0002.`;
}

/**
 * @param {string} baseUrl
 */
export function cursorRuleMdc(baseUrl) {
  return `---
name: ship-artifacts-protocol
description: Resolve, use, and record Ship artifacts (patterns/tools/workflows/collections) via shipctl.
---

${MARKER}

# Ship artifacts protocol (Cursor rule)

${protocolBody(baseUrl)}

${END_MARKER}
`;
}

/**
 * @param {string} baseUrl
 */
export function markdownSection(baseUrl) {
  return `

---

${MARKER}

## Ship artifacts protocol

${protocolBody(baseUrl)}
`;
}

/**
 * @param {string} baseUrl
 */
export function standaloneDoc(baseUrl) {
  return `# Ship artifacts protocol — agent reference

${MARKER}

Generated by \`shipctl init\`.

${protocolBody(baseUrl)}
`;
}

export { MARKER, END_MARKER };
