import { AppShell } from "@/components/app-shell";
import {
  Badge,
  ButtonDanger,
  ButtonGhost,
  ButtonPrimary,
  Card,
  CardHeader,
  MockBanner,
} from "@/components/ui";
import { actionItems, relativeTime, workspaces, yesterdayDigest } from "@/lib/mock/cloud";

const ws = workspaces[0];

export default function DailyRetroPage() {
  const proposed = actionItems.filter((a) => a.status === "proposed");
  const approved = actionItems.filter((a) => a.status === "approved");
  const rejected = actionItems.filter((a) => a.status === "rejected");

  return (
    <AppShell
      kicker={`${ws.name} · cadence`}
      title="Daily & retro"
      actions={
        <>
          <ButtonGhost>Replay yesterday</ButtonGhost>
          <ButtonPrimary>Run daily now</ButtonPrimary>
        </>
      }
    >
      <MockBanner />

      <section className="grid grid-cols-1 gap-5 lg:grid-cols-3">
        <Card className="lg:col-span-2">
          <CardHeader
            title={`Daily digest · ${yesterdayDigest.date}`}
            subtitle="Generated by the daily lane at 07:02 UTC"
            action={
              <span className="inline-flex items-center gap-2 text-[11px] text-white/55">
                <Badge tone="ok" dot>posted to #ship-daily</Badge>
              </span>
            }
          />
          <p className="text-sm leading-relaxed text-white/85">{yesterdayDigest.summary}</p>
          <div className="mt-6 grid grid-cols-1 gap-4 md:grid-cols-3">
            <DigestCol tone="ok" title="Shipped" items={yesterdayDigest.shipped} />
            <DigestCol tone="info" title="In flight" items={yesterdayDigest.inFlight} />
            <DigestCol tone="err" title="Blockers" items={yesterdayDigest.blockers} />
          </div>
        </Card>

        <Card>
          <CardHeader
            title="This week"
            subtitle="Action-item flow into the tracker"
          />
          <ul className="space-y-3 text-sm">
            <FlowRow label="Proposed" tone="warn" count={proposed.length} />
            <FlowRow label="Approved → tracker" tone="ok" count={approved.length} />
            <FlowRow label="Rejected" tone="err" count={rejected.length} />
            <li className="border-t border-white/10 pt-3 text-xs text-white/55">
              Approval rate{" "}
              <strong className="text-white">
                {Math.round((approved.length / (approved.length + rejected.length || 1)) * 100)}%
              </strong>
              <span className="ml-2">·</span>
              <span className="ml-2">last 7 days</span>
            </li>
          </ul>
        </Card>
      </section>

      <section className="mt-8">
        <h2 className="mb-3 font-display text-lg font-bold text-white">
          Proposed action items
          <span className="ml-2 align-middle text-xs font-semibold text-white/45">
            from daily / retro / self-heal lanes
          </span>
        </h2>
        <div className="space-y-3">
          {proposed.map((a) => (
            <Card key={a.id}>
              <div className="flex flex-col gap-3 lg:flex-row lg:items-start lg:justify-between">
                <div className="min-w-0 flex-1">
                  <div className="flex flex-wrap items-center gap-2">
                    <Badge
                      tone={a.severity === "high" ? "err" : a.severity === "med" ? "warn" : "info"}
                    >
                      {a.severity}
                    </Badge>
                    <Badge tone="neutral">{a.source}</Badge>
                    <span className="text-[11px] text-white/45">
                      proposed by{" "}
                      <span className="text-white/75">{a.proposedBy}</span> ·{" "}
                      {relativeTime(a.proposedAt)}
                    </span>
                    <span className="ml-auto rounded-full border border-white/10 bg-white/[0.04] px-2 py-0.5 text-[10px] font-semibold text-white/65">
                      {a.estimate}
                    </span>
                  </div>
                  <h3 className="mt-2 text-base font-semibold text-white">{a.title}</h3>
                  <p className="mt-1 max-w-3xl text-sm text-white/65">{a.reason}</p>
                </div>
                <div className="flex shrink-0 items-center gap-2">
                  <ButtonPrimary>Approve → Linear</ButtonPrimary>
                  <ButtonDanger>Reject</ButtonDanger>
                </div>
              </div>
            </Card>
          ))}
        </div>
      </section>

      <section className="mt-8 grid grid-cols-1 gap-5 lg:grid-cols-2">
        <Card>
          <CardHeader
            title="Approved this week"
            subtitle="Linked to your tracker; closed within 7 days counts toward retro follow-through KPI"
          />
          <ul className="divide-y divide-white/5">
            {approved.map((a) => (
              <li key={a.id} className="flex items-center justify-between gap-3 py-2.5">
                <div className="min-w-0">
                  <div className="truncate text-sm text-white">{a.title}</div>
                  <div className="text-[11px] text-white/50">
                    {a.source} · {relativeTime(a.proposedAt)}
                  </div>
                </div>
                <a
                  className="shrink-0 rounded-full border border-aqua/40 bg-aqua/10 px-2.5 py-1 font-mono text-[11px] font-bold text-aqua hover:bg-aqua/20"
                  href="#"
                >
                  {a.trackerKey}
                </a>
              </li>
            ))}
          </ul>
        </Card>
        <Card>
          <CardHeader
            title="Rejected · archived"
            subtitle="Kept for audit so the next retro can flag if the same item recurs"
          />
          <ul className="divide-y divide-white/5">
            {rejected.map((a) => (
              <li key={a.id} className="flex items-center justify-between gap-3 py-2.5">
                <div className="min-w-0">
                  <div className="truncate text-sm text-white/85">{a.title}</div>
                  <div className="text-[11px] text-white/50">
                    {a.source} · {relativeTime(a.proposedAt)}
                  </div>
                </div>
                <Badge tone="neutral">archived</Badge>
              </li>
            ))}
          </ul>
        </Card>
      </section>
    </AppShell>
  );
}

function DigestCol({
  tone,
  title,
  items,
}: {
  tone: "ok" | "info" | "err";
  title: string;
  items: string[];
}) {
  return (
    <div className="rounded-xl border border-white/10 bg-white/[0.02] p-3">
      <Badge tone={tone}>{title}</Badge>
      <ul className="mt-2 space-y-1.5 text-xs text-white/75">
        {items.map((item) => (
          <li key={item} className="leading-snug before:mr-2 before:content-['·'] before:text-white/30">
            {item}
          </li>
        ))}
      </ul>
    </div>
  );
}

function FlowRow({
  label,
  count,
  tone,
}: {
  label: string;
  count: number;
  tone: "ok" | "warn" | "err";
}) {
  return (
    <li className="flex items-center justify-between rounded-lg border border-white/10 bg-white/[0.02] px-3 py-2">
      <div className="flex items-center gap-2">
        <Badge tone={tone}>{label}</Badge>
      </div>
      <span className="font-display text-xl font-bold text-white">{count}</span>
    </li>
  );
}
